### ISSUE TITLE
Server Defean and mute

### ISSUE THREAD

**Issue by giren7384** [MiyFr/MiyuaTheme#1]
When you are server defeaned or muted there is the slightest color change and its hard to tell. Make it bright green or a different color

**Comment by giren7384** [comment]
.container-3baos1 .redIcon-2uP7Ej {
    color: #b075ff;
}
.strikethrough-1n4ekb {
    color: #b3aeff;
}

Normally muted
![image](https://user-images.githubusercontent.com/69572254/113370969-26e3a380-9333-11eb-95f7-d1736c0da8fc.png)


Server deafened and muted
![image](https://user-images.githubusercontent.com/69572254/113371018-4084eb00-9333-11eb-9093-f136847c2750.png)

**Comment by DesireRK** [comment]
i'll look into it

**Comment by giren7384** [comment]
I was looking here the second you said that, it was weird

**Comment by DesireRK** [comment]
Fixed, it should be included in a future update.
